apiVersion: cloudflare.io/v1
kind: CloudflareRecord
metadata:
  name: test-jeremygovi-cname
  namespace: default
spec:
  domain: "jeremygovi.win"
  name: "test"
  type: "CNAME"
  content: "www"
  ttl: 1
  proxied: false
  comment: "cname test record to www"
