apiVersion: cloudflare.io/v1
kind: CloudflareRecord
metadata:
  name: test-jeremygovi-a
  namespace: default
spec:
  domain: "jeremygovi.win"
  name: "www"
  type: "A"
  content: "185.214.53.1"
  ttl: 60
  proxied: false
  comment: "test A record"
