apiVersion: cloudflare.k8s.io/v1
kind: CloudflareRecord
metadata:
  name: test-jeremygovi-cname
  namespace: default
spec:
  zoneId: "2b47528563f073167e2e466aa26f2ecf"
  name: "test.jeremygovi.win"
  type: "CNAME"
  content: "www.google.com"
  ttl: 1
  proxied: false
  comment: "cname test record to google"
