apiVersion: cloudflare.k8s.io/v1
kind: CloudflareRecord
metadata:
  name: test-jeremygovi-a
  namespace: default
spec:
  zoneId: "2b47528563f073167e2e466aa26f2ecf"
  name: "www.jeremygovi.win"
  type: "A"
  content: "185.214.53.1"
  ttl: 3600
  proxied: true
  comment: "test A record"
