apiVersion: cloudflare.io/v1
kind: CloudflareRuleset
metadata:
  name: redirect-rules-test
  namespace: default
spec:
  zoneId: "2b47528563f073167e2e466aa26f2ecf"
  name: "TEST Redirect Rules"
  description: "URL redirects for legacy paths"
  phase: "http_request_dynamic_redirect"
  rules:
    - action: "redirect"
      expression: "(http.request.uri.path eq \"/old-path\")"
      description: "Redirect old path to new location"
      enabled: true
      actionParameters:
        from_value:
          status_code: 301
          target_url:
            value: "https://www.jeremygovi.win/new-path"
